// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: courses.sql

package pgstore

import (
	"context"
)

const getCourses = `-- name: GetCourses :many
SELECT
    "course_id",
    "code",
    "name",
    "workload",
    "department",
    "program",
    "objective",
    "content",
    "bibliography",
    "created_at",
    "updated_at"
FROM
    "courses"
ORDER BY
    "name" ASC
`

func (q *Queries) GetCourses(ctx context.Context) ([]Course, error) {
	rows, err := q.db.Query(ctx, getCourses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Course
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.CourseID,
			&i.Code,
			&i.Name,
			&i.Workload,
			&i.Department,
			&i.Program,
			&i.Objective,
			&i.Content,
			&i.Bibliography,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
