// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package pgstore

import (
	"time"
)

type Course struct {
	CourseID     int32
	Code         string
	Name         string
	Workload     int32
	Department   string
	Program      *string
	Objective    *string
	Content      *string
	Bibliography *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Discipline struct {
	DisciplineID int32
	Code         string
	Name         string
	Workload     int32
	Department   string
	Program      *string
	Objective    *string
	Content      *string
	Bibliography *string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Relation struct {
	CourseID     int32
	DisciplineID int32
	RelationType string
}
